@Backend_HostAddress = http://localhost:8080/

GET {{Backend_HostAddress}} /
Accept: application/json
###

GET {{Backend_HostAddress}}api/HealthCheck/app
Accept: application/json
###

GET {{Backend_HostAddress}}api/HealthCheck/database
Accept: application/json
###

GET {{Backend_HostAddress}}api/HealthCheck/RabbitMq
Accept: application/json
###

GET {{Backend_HostAddress}}api/HealthCheck/Minio
Accept: application/json
###

GET {{Backend_HostAddress}}api/HealthCheck/redis
Accept: application/json
###

GET {{Backend_HostAddress}}api/File
Accept: application/json
###

POST {{Backend_HostAddress}}api/File
Accept: application/json
Content-Type: application/json

{
  "fileName": "example.txt",
  "base64Content": "SGVsbG8sIE1pbnJvISBUaGlzIGlzIGEgZmlsZS4="
}

